name: Docker

on:
  push:
    branches:
      - master
      - develop
      - hotfix/**
      - feature/**
      - renovate/**

jobs:
  github-actions:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Ubuntu
            version: ubuntu-latest
        java:
          - name: Corretto 17
            distribution: corretto
            version: 17
        project:
          - name: ActiveMQ - Producer
            image-name: active-producer
            working-directory: ./active/producer
          - name: ActiveMQ - Consumer
            image-name: active-consumer
            working-directory: ./active/consumer
          - name: gRPC - Producer
            image-name: grpc-producer
            working-directory: ./grpc/producer
          - name: gRPC - Consumer
            image-name: grpc-consumer
            working-directory: ./grpc/consumer
          - name: Kafka - Producer
            image-name: kafka-producer
            working-directory: ./kafka/producer
          - name: Kafka - Consumer
            image-name: kafka-consumer
            working-directory: ./kafka/consumer
          - name: RabbitMQ - Producer
            image-name: rabbit-producer
            working-directory: ./rabbit/producer
          - name: RabbitMQ - Consumer
            image-name: rabbit-consumer
            working-directory: ./rabbit/consumer
          - name: Redis - Producer
            image-name: redis-producer
            working-directory: ./redis/producer
          - name: Redis - Consumer
            image-name: redis-consumer
            working-directory: ./redis/consumer
    name: ${{ matrix.os.name }} - ${{ matrix.java.name }} - ${{ matrix.project.name }}
    runs-on: ${{ matrix.os.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java.distribution }}
          java-version: ${{ matrix.java.version }}
      - name: Branch
        run: echo ${{ github.head_ref || github.ref_name }}
      - name: TimeZone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: 'Asia/Ho_Chi_Minh'
      - name: Get Date & Time
        id: datetime
        run: |
          echo $(date +'%Y-%m-%dT%H:%M:%S')
          echo "::set-output name=datetime::$(date +'%Y%m%d.%H%M%S')"
      - name: Get Commit SHA
        id: version
        run: |
          echo $(git rev-parse --short HEAD)
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Update Tools
        run: sudo apt-get update && sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
      - name: Add Repository & Install Docker
        run:
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - &&
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" &&
          sudo apt-get update &&
          sudo apt-get install docker-ce
      - name: Build JAR
        run: ./gradlew jar
        working-directory: ${{ matrix.project.working-directory }}
      - name: Docker Build
        run: docker build . --no-cache -t ${{ matrix.project.image-name }}:$IMAGE_TAG
        working-directory: ${{ matrix.project.working-directory }}
        env:
          IMAGE_TAG: ${{ github.head_ref || github.ref_name }}.${{ steps.datetime.outputs.datetime }}.${{ steps.version.outputs.sha_short }}
