DROP SCHEMA IF EXISTS public;

CREATE SCHEMA IF NOT EXISTS public;

DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users (
	id				VARCHAR		NOT NULL,
	username		VARCHAR		NOT NULL DEFAULT '',
	password		VARCHAR		NOT NULL DEFAULT '',
	created_at		TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at		TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.lists;

CREATE TABLE IF NOT EXISTS public.lists (
	id				VARCHAR		NOT NULL,
	title			VARCHAR		NOT NULL DEFAULT '',
	description		VARCHAR		NOT NULL DEFAULT '',
	userId			VARCHAR		NOT NULL DEFAULT '',
	created_at		TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at		TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY (id)
);


DROP TABLE IF EXISTS public.tasks;

CREATE TABLE IF NOT EXISTS public.tasks (
	id				VARCHAR		NOT NULL,
	title			VARCHAR		NOT NULL DEFAULT '',
	description		VARCHAR		NOT NULL DEFAULT '',
	listId			VARCHAR		NOT NULL DEFAULT '',
	completed		BOOLEAN		NOT NULL DEFAULT false,
	created_at		TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at		TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);
